repos:
    - repo: local
      hooks:
        - id: black
          name: black
          entry: black
          require_serial: true
          language: python
          types_or: [python, pyi]
        - id: flake8
          name: flake8
          entry: flake8
          require_serial: true
          language: python
          types_or: [python, pyi]
default_language_version:
    python: python3.11